version: '3.8'

services:
  mafl:
    image: ghcr.io/hywax/mafl
    restart: unless-stopped
    ports:
      - '3888:3000'
    volumes:
      - ./data:/app/data
      - ./data/favicons/favicon.png:/app/icons/favicon.png
